// Daftar 114 surah ditanam langsung di dalam app, supaya daftar surah
// tetap tampil walau koneksi internet lambat / belum siap saat app dibuka.
// Data ayat, audio, dan terjemah tetap diambil dari internet saat surah dibuka.
const SURAH_DATA = [
  [1,"الفاتحة","Al-Fatihah","Pembukaan",7],[2,"البقرة","Al-Baqarah","Sapi Betina",286],
  [3,"آل عمران","Ali 'Imran","Keluarga Imran",200],[4,"النساء","An-Nisa","Wanita",176],
  [5,"المائدة","Al-Ma'idah","Hidangan",120],[6,"الأنعام","Al-An'am","Binatang Ternak",165],
  [7,"الأعراف","Al-A'raf","Tempat Tertinggi",206],[8,"الأنفال","Al-Anfal","Harta Rampasan Perang",75],
  [9,"التوبة","At-Taubah","Pengampunan",129],[10,"يونس","Yunus","Nabi Yunus",109],
  [11,"هود","Hud","Nabi Hud",123],[12,"يوسف","Yusuf","Nabi Yusuf",111],
  [13,"الرعد","Ar-Ra'd","Guruh",43],[14,"ابراهيم","Ibrahim","Nabi Ibrahim",52],
  [15,"الحجر","Al-Hijr","Gunung Al Hijr",99],[16,"النحل","An-Nahl","Lebah",128],
  [17,"الإسراء","Al-Isra","Perjalanan Malam",111],[18,"الكهف","Al-Kahf","Gua",110],
  [19,"مريم","Maryam","Maryam",98],[20,"طه","Ta-Ha","Ta Ha",135],
  [21,"الأنبياء","Al-Anbiya","Para Nabi",112],[22,"الحج","Al-Hajj","Haji",78],
  [23,"المؤمنون","Al-Mu'minun","Orang-orang Mukmin",118],[24,"النور","An-Nur","Cahaya",64],
  [25,"الفرقان","Al-Furqan","Pembeda",77],[26,"الشعراء","Asy-Syu'ara","Para Penyair",227],
  [27,"النمل","An-Naml","Semut",93],[28,"القصص","Al-Qasas","Kisah-kisah",88],
  [29,"العنكبوت","Al-'Ankabut","Laba-laba",69],[30,"الروم","Ar-Rum","Bangsa Romawi",60],
  [31,"لقمان","Luqman","Luqman",34],[32,"السجدة","As-Sajdah","Sujud",30],
  [33,"الأحزاب","Al-Ahzab","Golongan yang Bersekutu",73],[34,"سبإ","Saba","Kaum Saba",54],
  [35,"فاطر","Fatir","Pencipta",45],[36,"يس","Ya-Sin","Ya Sin",83],
  [37,"الصافات","As-Saffat","Yang Bersaf-saf",182],[38,"ص","Sad","Sad",88],
  [39,"الزمر","Az-Zumar","Rombongan",75],[40,"غافر","Ghafir","Yang Mengampuni",85],
  [41,"فصلت","Fussilat","Yang Dijelaskan",54],[42,"الشورى","Asy-Syura","Musyawarah",53],
  [43,"الزخرف","Az-Zukhruf","Perhiasan",89],[44,"الدخان","Ad-Dukhan","Kabut",59],
  [45,"الجاثية","Al-Jasiyah","Yang Berlutut",37],[46,"الأحقاف","Al-Ahqaf","Bukit-bukit Pasir",35],
  [47,"محمد","Muhammad","Nabi Muhammad",38],[48,"الفتح","Al-Fath","Kemenangan",29],
  [49,"الحجرات","Al-Hujurat","Kamar-kamar",18],[50,"ق","Qaf","Qaf",45],
  [51,"الذاريات","Az-Zariyat","Angin yang Menerbangkan",60],[52,"الطور","At-Tur","Bukit Tursina",49],
  [53,"النجم","An-Najm","Bintang",62],[54,"القمر","Al-Qamar","Bulan",55],
  [55,"الرحمن","Ar-Rahman","Yang Maha Pengasih",78],[56,"الواقعة","Al-Waqi'ah","Hari Kiamat",96],
  [57,"الحديد","Al-Hadid","Besi",29],[58,"المجادلة","Al-Mujadilah","Wanita yang Mengajukan Gugatan",22],
  [59,"الحشر","Al-Hasyr","Pengusiran",24],[60,"الممتحنة","Al-Mumtahanah","Wanita yang Diuji",13],
  [61,"الصف","As-Saff","Barisan",14],[62,"الجمعة","Al-Jumu'ah","Hari Jumat",11],
  [63,"المنافقون","Al-Munafiqun","Orang-orang Munafik",11],[64,"التغابن","At-Tagabun","Hari Ditampakkan Kesalahan",18],
  [65,"الطلاق","At-Talaq","Talak",12],[66,"التحريم","At-Tahrim","Mengharamkan",12],
  [67,"الملك","Al-Mulk","Kerajaan",30],[68,"القلم","Al-Qalam","Pena",52],
  [69,"الحاقة","Al-Haqqah","Hari Kiamat",52],[70,"المعارج","Al-Ma'arij","Tempat Naik",44],
  [71,"نوح","Nuh","Nabi Nuh",28],[72,"الجن","Al-Jinn","Jin",28],
  [73,"المزمل","Al-Muzzammil","Orang yang Berselimut",20],[74,"المدثر","Al-Muddassir","Orang yang Berkemul",56],
  [75,"القيامة","Al-Qiyamah","Hari Kiamat",40],[76,"الانسان","Al-Insan","Manusia",31],
  [77,"المرسلات","Al-Mursalat","Malaikat yang Diutus",50],[78,"النبإ","An-Naba","Berita Besar",40],
  [79,"النازعات","An-Nazi'at","Malaikat yang Mencabut",46],[80,"عبس","'Abasa","Ia Bermuka Masam",42],
  [81,"التكوير","At-Takwir","Menggulung",29],[82,"الإنفطار","Al-Infitar","Terbelah",19],
  [83,"المطففين","Al-Mutaffifin","Orang-orang yang Curang",36],[84,"الإنشقاق","Al-Insyiqaq","Terbelah",25],
  [85,"البروج","Al-Buruj","Gugusan Bintang",22],[86,"الطارق","At-Tariq","Yang Datang di Malam Hari",17],
  [87,"الأعلى","Al-A'la","Yang Paling Tinggi",19],[88,"الغاشية","Al-Gasyiyah","Hari Pembalasan",26],
  [89,"الفجر","Al-Fajr","Fajar",30],[90,"البلد","Al-Balad","Negeri",20],
  [91,"الشمس","Asy-Syams","Matahari",15],[92,"الليل","Al-Lail","Malam",21],
  [93,"الضحى","Ad-Duha","Waktu Duha",11],[94,"الشرح","Asy-Syarh","Kelapangan",8],
  [95,"التين","At-Tin","Buah Tin",8],[96,"العلق","Al-'Alaq","Segumpal Darah",19],
  [97,"القدر","Al-Qadr","Kemuliaan",5],[98,"البينة","Al-Bayyinah","Bukti Nyata",8],
  [99,"الزلزلة","Az-Zalzalah","Kegoncangan",8],[100,"العاديات","Al-'Adiyat","Kuda Perang yang Berlari Kencang",11],
  [101,"القارعة","Al-Qari'ah","Hari Kiamat",11],[102,"التكاثر","At-Takasur","Bermegah-megahan",8],
  [103,"العصر","Al-'Asr","Masa",3],[104,"الهمزة","Al-Humazah","Pengumpat",9],
  [105,"الفيل","Al-Fil","Gajah",5],[106,"قريش","Quraisy","Suku Quraisy",4],
  [107,"الماعون","Al-Ma'un","Barang-barang yang Berguna",7],[108,"الكوثر","Al-Kausar","Nikmat yang Berlimpah",3],
  [109,"الكافرون","Al-Kafirun","Orang-orang Kafir",6],[110,"النصر","An-Nasr","Pertolongan",3],
  [111,"المسد","Al-Masad","Sabut",5],[112,"الإخلاص","Al-Ikhlas","Memurnikan Keesaan Allah",4],
  [113,"الفلق","Al-Falaq","Waktu Subuh",5],[114,"الناس","An-Nas","Manusia",6]
].map(x=>({ number:x[0], name:x[1], englishName:x[2], englishNameTranslation:x[3], numberOfAyahs:x[4] }));